name: Deploy pull request previews to Pages

on:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: ${{ github.event.pull_request.head.ref }}
      - name: Setup Pages
        uses: actions/configure-pages@v3
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v2
        with:
          path: "."
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v2

  create_pull_request_comment:
    needs: deploy
    if: always() && github.event_name == 'pull_request'
    runs-on: ubuntu-latest
    steps:
      - name: Create pull request comment
        uses: actions/github-script@v5
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const context = github.context;
            const deploymentURL = context.payload.repository.html_url + '/deployments/' + context.runId;
            const comment = `Preview URL: ${deploymentURL}`;
            const owner = context.payload.repository.owner.login;
            const repo = context.payload.repository.name;
            const issue_number = context.payload.pull_request.number;

            github.issues.createComment({
              owner,
              repo,
              issue_number,
              body: comment
            });
